name: demoweb_app
description: e8yes demoweb web front end.
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  grpc: ^2.8.0
  random_string: ^2.1.0
  webstorage: ^2.0.0

dev_dependencies:
  build_runner: ^1.10.9
  build_web_compilers: ^2.12.0
  sass_builder: ^2.1.3
