name: demoweb_app
description: e8yes demoweb web front end.
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha
  grpc: ^2.1.3
  random_string: ^2.0.1
  webstorage: ^2.0.0

dev_dependencies:
  build_runner: ^1.5.1
  build_web_compilers: ^2.1.0
  sass_builder: ^2.1.3
