version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Initialize Environment
          command: cd server && make init
      - checkout
      - run:
          name: Run maven test
          command: cd server && make test
