apiVersion: v1
kind: Service 
metadata:
  name: demoweb-service
spec:
  type: LoadBalancer
  ports:
    - port: 50051 
      targetPort: 50051
  selector:
    app: demoweb-service-app
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoweb-service-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demoweb-service-app
  template:
    metadata:
      labels:
        app: demoweb-service-app
    spec:
      containers:
      - name: demoweb-service-container
        image: DEMOWEB_SERVICE_IMAGE
        ports:
        - containerPort: 50051
